--https://programmers.co.kr/learn/courses/30/lessons/59411
--MySQL
--오랜기간 보호한 동물
--1.보호기간이 긴 동물 2마리만 조회

-- MySQL
SELECT A.ANIMAL_ID, A.NAME
 FROM ANIMAL_INS AS A 
      JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME)
LIMIT 2

--SQL SERVER 
SELECT TOP 2 A.ANIMAL_ID, A.NAME
 FROM ANIMAL_INS AS A 
      JOIN ANIMAL_OUTS AS B ON A.ANIMAL_ID = B.ANIMAL_ID
ORDER BY DATEDIFF(A.DATETIME, B.DATETIME)

